package Java_8_feature.streamOperation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

public class StreamCreationWay {

    public static void main(String[] args) {
        System.out.println("Empty Stream");
        Stream<String> emptyStream = Stream.empty();
        System.out.println(emptyStream.count());
        System.out.println();

        System.out.println("Stream Collection");//list, set etc;
        List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        Stream<Integer> stream = list.stream();
        stream.forEach(System.out::println);
        System.out.println();

        System.out.println("Stream Of Array");
        String[] arr = {"Avinash","Surwase"};
        Stream<String> stream1 = Arrays.stream(arr);
        stream1.forEach(System.out::println);
        System.out.println();

        System.out.println("Stream.builder()");
        //The Stream.builder method is used to create a stream in a flexible manner.
        Stream<String> builder = Stream.<String>builder().add("Avinash").add("Surwase").build();
        builder.forEach(System.out::println);
        System.out.println();

        System.out.println("Stream.generate()");
        //The Stream.generate method creates an infinite stream of elements generated by a supplier.
        Stream<Double> generate = Stream.generate(Math::random).limit(3);
        generate.forEach(System.out::println);
        System.out.println();

        System.out.println("Stream.iterate()");
        //iterate() method create an infinite stream of elements
        Stream<Integer> iterate = Stream.iterate(2,n -> n * 2).limit(3);
        iterate.forEach(System.out::println);

    }
}
